import{test}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{APAS_COMPATIBILITY_CORPUS_KIND,APAS_COMPATIBILITY_SCHEMA_VERSION,compatibilityPassport,compatibilityReport,parseCompatibilityCorpus,parseCompatibilityReport,summarizeCompatibilityCorpus}from'../packages/core/compatibility.ts';
import type{StudentAcademicProfile,StudentCourse}from'../packages/schemas/index.ts';

const now='2026-09-28T03:30:00.000Z',prov={source:'fixture',retrievedAt:now,period:'fixture'};
const transfer=(courseCode:string,transferSource:string):StudentCourse=>({courseCode,campus:'UMNTC',subject:courseCode.split(' ')[0],number:courseCode.split(' ')[1],credits:3,grade:'',status:'transfer',transferSource});
function profile():StudentAcademicProfile{return{program:{name:'Private Synthetic Name',kind:'degree',campus:'UMNTC'},degreeCredits:{},completedCourses:[],inProgressCourses:[{courseCode:'PRIVATE 9999',campus:'UMNTC',credits:3,status:'in_progress'}],transferCourses:[transfer('MATH 1271','Advanced Placement / Calculus BC'),transfer('PHYS 1301','International Baccalaureate / Physics HL'),transfer('CHEM 1015','CLEP / Chemistry'),transfer('HIST 1001','Example External University')],requirements:[
 {id:'strict',label:'Private strict label',status:'incomplete',coursesUsed:[],children:[],rule:{type:'course',code:'PSY 1001',campus:'UMNTC'},rawMetadata:{}},
 {id:'candidate',label:'Private candidate label',status:'incomplete',coursesUsed:[],children:[],rule:{type:'unknown',sourceText:'private',reason:'review' },candidateRule:{type:'range',subject:'HIST',min:3000,max:4999,campus:'UMNTC'},rawMetadata:{}},
 {id:'policy',label:'Private policy label',status:'incomplete',coursesUsed:[],children:[],rule:{type:'policy',family:'degree-credits',sourceText:'private',reason:'review',parameters:{minimumCredits:120}},rawMetadata:{}}
 ],additionalPrograms:[{program:{name:'Private Minor',kind:'minor',campus:'UMNTC'},requirements:[],syncedAt:now,parserVersion:'0.4.5',warnings:[],provenance:prov}],syncedAt:now,parserVersion:'0.4.5',warnings:['fixture warning'],provenance:prov};}

test('compatibility report exposes structural counts and test-credit cohorts without private course data',()=>{const p=profile(),passport=compatibilityPassport(p),report=compatibilityReport(p,now),json=JSON.stringify(report);assert.equal(passport.schemaVersion,1);assert.deepEqual(passport.programKinds,['degree','minor']);assert.equal(passport.apCreditCount,1);assert.equal(passport.ibCreditCount,1);assert.equal(passport.otherTestCreditCount,1);assert.equal(passport.nonTestTransferCount,1);assert.equal(passport.transferCourseCount,4);assert.equal(passport.inProgressCourseCount,1);assert.equal(report.kind,'smart-umn-anonymous-apas-compatibility');assert.doesNotMatch(json,/Private Synthetic Name|Private Minor|PRIVATE 9999|MATH 1271|Calculus BC|Example External University/);assert.deepEqual(parseCompatibilityReport(report),report);});

test('compatibility schema rejects extra identity fields and inconsistent accounting',()=>{const r=compatibilityReport(profile(),now);assert.throws(()=>parseCompatibilityReport({...r,programName:'Private Synthetic Name'}),/forbidden field programName/);assert.throws(()=>parseCompatibilityReport({...r,openRequirements:r.openRequirements+1}),/Coverage buckets must sum/);assert.throws(()=>parseCompatibilityReport({...r,transferCourseCount:r.transferCourseCount+1}),/Transfer cohorts must sum/);});

test('compatibility corpus rejects duplicate structures and summarizes anonymous cohorts',()=>{const r=compatibilityReport(profile(),now),corpus=parseCompatibilityCorpus({kind:APAS_COMPATIBILITY_CORPUS_KIND,schemaVersion:APAS_COMPATIBILITY_SCHEMA_VERSION,reports:[r]}),s=summarizeCompatibilityCorpus(corpus);assert.equal(s.reports,1);assert.equal(s.uniqueFingerprints,1);assert.equal(s.multiProgramReports,1);assert.equal(s.apCreditReports,1);assert.equal(s.ibCreditReports,1);assert.equal(s.otherTestCreditReports,1);assert.equal(s.nonTestTransferReports,1);assert.equal(s.inProgressReports,1);assert.equal(s.warningReports,1);assert.throws(()=>parseCompatibilityCorpus({kind:APAS_COMPATIBILITY_CORPUS_KIND,schemaVersion:1,reports:[r,{...r,generatedAt:'2026-09-28T03:31:00.000Z'}]}),/Duplicate anonymous compatibility structure/);});

test('checked-in real compatibility corpus is schema-valid and release-clean',()=>{const raw=JSON.parse(fs.readFileSync(new URL('../docs/evidence/apas-compatibility-corpus.json',import.meta.url),'utf8')),s=summarizeCompatibilityCorpus(parseCompatibilityCorpus(raw));assert.ok(s.reports>=1);assert.ok(s.uniqueFingerprints>=1);assert.equal(s.unresolvedReports,0);assert.equal(s.unclassifiedPolicyReports,0);});
