import{test}from'node:test';import assert from'node:assert/strict';
import{publicCourseCoverageMarkdown,subjectCoverage,summarizePublicCourseCoverage}from'../packages/core/course-coverage.ts';
import type{Course}from'../packages/schemas/index.ts';
const now='2026-09-28T04:00:00.000Z',prov={source:'fixture',retrievedAt:now,period:'1273'};
function course(code:string,opts:Partial<Course>={}):Course{const[subject,catalogNumber]=code.split(' ');return{institution:'UMNTC',campus:'UMNTC',term:'1273',subject,catalogNumber,code,title:code+' title',description:'Description',credits:3,prerequisites:'',prerequisiteRule:{type:'unknown',sourceText:'',reason:'No prerequisite information supplied'},attributes:[],sectionIds:['1'],equivalents:[],sourceRefs:{scheduleBuilder:'https://schedulebuilder.umn.edu/'},provenance:prov,...opts};}
test('subject coverage deduplicates current courses and separates published prerequisite parsing',()=>{const rows=subjectCoverage({subject:'CSCI',scheduleBuilderStatus:'healthy',gopherGradesStatus:'available',historicalCourseCodes:new Set(['CSCI 1001']),courses:[
 course('CSCI 1001',{prerequisites:'prereq: MATH 1271',prerequisiteRule:{type:'course',code:'MATH 1271',campus:'UMNTC'},attributes:['{"attribute":"CLE","attribute_value":"MATH"}']}),
 course('CSCI 1001',{title:'duplicate'}),
 course('CSCI 2001',{description:'',credits:undefined,sectionIds:[],prerequisites:'prereq: junior standing',prerequisiteRule:{type:'unknown',sourceText:'junior standing',reason:'Standing requires review'}})
]});assert.deepEqual(rows,{subject:'CSCI',currentCourses:2,gradeCoveredCourses:1,descriptionCourses:1,creditsKnownCourses:1,sectionIndexedCourses:1,publishedPrerequisiteCourses:2,parsedPublishedPrerequisiteCourses:1,attributeTaggedCourses:1,scheduleBuilderStatus:'healthy',gopherGradesStatus:'available'});});
test('campus-wide summary keeps optional historical/community evidence separate from official course coverage',()=>{const a=subjectCoverage({subject:'A',scheduleBuilderStatus:'healthy',gopherGradesStatus:'available',historicalCourseCodes:new Set(['A 1000']),courses:[course('A 1000'),course('A 2000',{description:''})]}),b=subjectCoverage({subject:'B',scheduleBuilderStatus:'degraded',gopherGradesStatus:'missing',historicalCourseCodes:new Set(),courses:[course('B 1000',{sectionIds:[]})]}),s=summarizePublicCourseCoverage([a,b],now,'1273',{courseReferences:2,coursesWithReferences:1});assert.equal(s.currentCourses,3);assert.equal(s.subjects.scheduleBuilderHealthy,1);assert.equal(s.subjects.scheduleBuilderDegraded,1);assert.equal(s.historical.gradeCoveredCourses,1);assert.equal(s.historical.gradeCoveragePercent,33.3);assert.equal(s.community.policy,'curated-link-only');assert.equal(s.community.coursesWithReferences,1);});
test('coverage markdown makes missing optional layers explicit instead of claiming full intelligence',()=>{const row=subjectCoverage({subject:'TEST',scheduleBuilderStatus:'healthy',gopherGradesStatus:'missing',historicalCourseCodes:new Set(),courses:[course('TEST 1000')]});const md=publicCourseCoverageMarkdown(summarizePublicCourseCoverage([row],now,'1273',{courseReferences:0,coursesWithReferences:0}));assert.match(md,/1 current Schedule Builder courses/);assert.match(md,/historical GopherGrades records: \*\*0 \/ 1 \(0%\)\*\*/);assert.match(md,/does \*\*not\*\* report a separate offering-history coverage percentage/);assert.match(md,/does \*\*not\*\* mean every course has grades, professor ratings or community discussion/);});
