import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
const bundle=await build({entryPoints:['apps/web/app.ts'],bundle:true,write:false,format:'iife',platform:'browser'});
const source=bundle.outputFiles[0].text;
const profile={program:{name:'Synthetic BA',campus:'UMNTC'},degreeCredits:{},completedCourses:[],inProgressCourses:[],transferCourses:[],additionalPrograms:[],syncedAt:'2026-09-27T00:00:00Z',parserVersion:'test',warnings:[],provenance:{source:'fixture',retrievedAt:'2026-09-27T00:00:00Z'},requirements:[{id:'r0',label:'First route',status:'incomplete',children:[],coursesUsed:[],rawMetadata:{},rule:{type:'course',code:'PSY 1001',campus:'UMNTC'}},{id:'r1',label:'Second route',status:'incomplete',children:[],coursesUsed:[],rawMetadata:{},rule:{type:'course',code:'HIST 1001',campus:'UMNTC'}}]};
function setup(){const dom=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'http://127.0.0.1:4317/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;Object.assign(w,{CSS:{escape:(s:string)=>s.replace(/[^a-zA-Z0-9_-]/g,c=>'\\'+c)},matchMedia:()=>({matches:true}),fetch:async()=>({ok:true,json:async()=>({data:[]})})});w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.localStorage.setItem('umn.profile',JSON.stringify(profile));w.localStorage.setItem('umn.focus',JSON.stringify({program:profile.program.name,route:'r0'}));w.eval(source);return dom;}
function click(dom:JSDOM,selector:string){(dom.window.document.querySelector(selector) as HTMLElement).click();}
function state(dom:JSDOM,p:unknown){const w=dom.window;w.dispatchEvent(new w.MessageEvent('message',{source:w as unknown as Window,origin:w.location.origin,data:{channel:'smart-umn-extension',type:'STATE',payload:{profile:p}}}));}
test('extension state preserves the chosen APAS focus across repeated messages',()=>{const d=setup();try{state(d,profile);click(d,'[data-panel="degree"]');assert.match(d.window.document.querySelector('#drawer .notice')!.textContent!,/1 recognized course routes/);}finally{d.window.close();}});
test('planning goal stays selected after navigation and credit preference edits',()=>{const d=setup();try{const w=d.window,doc=w.document;const light=doc.querySelector<HTMLInputElement>('[name="planning-goal"][value="lightLoad"]')!;light.click();assert.equal(JSON.parse(w.localStorage.getItem('umn.preferences')!).planningGoal,'lightLoad');click(d,'[data-nav="Explore"]');click(d,'[data-nav="Plan"]');assert.equal(doc.querySelector<HTMLInputElement>('[name="planning-goal"]:checked')?.value,'lightLoad');const details=doc.querySelector<HTMLDetailsElement>('#preferences')!;details.open=true;const min=doc.querySelector<HTMLInputElement>('#min')!;min.value='1';min.dispatchEvent(new w.Event('change'));assert.equal(JSON.parse(w.localStorage.getItem('umn.preferences')!).planningGoal,'lightLoad');assert.equal(JSON.parse(w.localStorage.getItem('umn.preferences')!).minCredits,1);}finally{d.window.close();}});
test('syncing another program clears a saved schedule from the previous program',()=>{const d=setup();try{const w=d.window;state(d,profile);w.dispatchEvent(new w.MessageEvent('message',{source:w as unknown as Window,origin:w.location.origin,data:{channel:'smart-umn-extension',type:'STATE',payload:{plans:[{name:'Test snapshot',term:'1273',schedule:{credits:3,campusDays:1,courses:[],sections:[],explanations:[]}}]}}}));click(d,'[data-panel="saved"]');click(d,'[data-load="0"]');assert.ok(w.document.querySelector('.schedule'));state(d,{...profile,program:{name:'Synthetic BSN',campus:'UMNTC'}});assert.equal(w.document.querySelector('.schedule'),null);assert.equal((w.document.querySelector('#focus') as HTMLSelectElement).value,'');}finally{d.window.close();}});
test('closing a dialog restores keyboard focus to its replacement trigger',()=>{const d=setup();try{const b=d.window.document.querySelector('[data-panel="degree"]') as HTMLElement;b.focus();b.click();click(d,'#close-panel');assert.equal((d.window.document.activeElement as HTMLElement).dataset.panel,'degree');}finally{d.window.close();}});

test('an old pending course lookup cannot reopen after another APAS import',async()=>{const d=setup();try{const w=d.window;let resolve:(value:unknown)=>void=()=>{};w.fetch=(()=>new Promise<unknown>(r=>{resolve=r;})) as unknown as typeof fetch;click(d,'[data-nav="Explore"]');const query=w.document.querySelector('#query') as HTMLInputElement;query.value='PSY 1001';w.document.querySelector('#search')!.dispatchEvent(new w.Event('submit',{cancelable:true}));state(d,{...profile,program:{name:'Synthetic BFA',campus:'UMNTC'}});resolve({ok:true,json:async()=>[{course:{data:{code:'PSY 1001',title:'Old response'}}}]});await new Promise(r=>setTimeout(r,0));assert.equal(w.document.querySelector('#drawer'),null);assert.equal(w.document.querySelector('.loading'),null);}finally{d.window.close();}});
