import{academicProfile,savedPlans,STORAGE_VERSION}from'../../packages/storage/validation.ts';
import type{StudentAcademicProfile,CourseContext,Course}from'../../packages/schemas/index.ts';import{campusCode,courseCode,termCode}from'../../packages/schemas/index.ts';import{mergeProgramAudit}from'../../packages/apas-parser/index.ts';import{enrichGeneralEducation}from'../../packages/core/general-education.ts';
import{WEB_ORIGIN as WEB}from'../../packages/config/origin.ts';const APAS='https://umn.uachieve.com/selfservice';
chrome.runtime.onInstalled.addListener(()=>{void chrome.storage.local.setAccessLevel({accessLevel:'TRUSTED_CONTEXTS'});void chrome.storage.local.get('storageVersion').then(s=>{if(s.storageVersion===undefined||s.storageVersion===0||s.storageVersion===STORAGE_VERSION)return chrome.storage.local.set({storageVersion:STORAGE_VERSION});});void chrome.alarms.create('apas-sync',{periodInMinutes:360});});
chrome.action.onClicked.addListener(()=>{void chrome.tabs.create({url:WEB});});
async function connect(interactive=true,requestedProgram?:string){const state=await chrome.storage.local.get(['syncTab']);const syncState={syncStarted:Date.now(),status:'Connecting to UMN',...(requestedProgram?{requestedProgram}:{} as object)};if(state.syncTab){try{await chrome.storage.local.set(syncState);await chrome.tabs.update(Number(state.syncTab),{active:interactive,url:APAS});return;}catch{}}
 const tab=await chrome.tabs.create({url:APAS,active:interactive});await chrome.storage.local.set({syncTab:tab.id,...syncState});}
chrome.alarms.onAlarm.addListener(async alarm=>{if(alarm.name==='apas-sync'){const{profile}=await chrome.storage.local.get('profile');if(profile)await connect(false);}});
chrome.tabs.onRemoved.addListener(async id=>{const state=await chrome.storage.local.get('syncTab');if(state.syncTab===id)await chrome.storage.local.remove('syncTab');});
chrome.tabs.onUpdated.addListener(async(id,info)=>{const state=await chrome.storage.local.get('syncTab');if(id===state.syncTab&&info.url){const u=new URL(info.url);if(u.origin!=='https://umn.uachieve.com'){await chrome.storage.local.set({status:'UMN session expired — reconnect and complete official sign-in'});await chrome.tabs.update(id,{active:true});}}});
const cache=new Map<string,{at:number;value:CourseContext}>();
async function batch(codes:unknown,term:unknown,campus:unknown){if(!Array.isArray(codes)||codes.length>12)throw Error('Invalid course batch');const t=termCode(String(term)),cp=campusCode(String(campus||'UMNTC'));if(cp!=='UMNTC')throw Error('Smart UMN currently supports Twin Cities Schedule Builder only');const cs=codes.map(c=>courseCode(String(c))),key=(c:string)=>cp+':'+t+':'+c;const missing=cs.filter(c=>!cache.has(key(c))||Date.now()-cache.get(key(c))!.at>30000);if(missing.length){const response=await fetch(WEB+'/api/course-context/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({codes:missing,term:t,campus:cp}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Planner public-data API unavailable');const values:CourseContext[]=await response.json();for(const v of values)if(v.course.data)cache.set(key(v.course.data.code),{at:Date.now(),value:v});}return cs.map(c=>cache.get(key(c))?.value).filter(Boolean);}
chrome.runtime.onMessage.addListener((m,sender,respond)=>{
 const senderUrl=sender.url||'';const apas=senderUrl.startsWith(APAS+'/');const web=senderUrl.startsWith(WEB+'/');let sb=false;try{const u=new URL(senderUrl);sb=u.protocol==='https:'&&u.hostname==='schedulebuilder.umn.edu';}catch{}const internal=senderUrl.startsWith(chrome.runtime.getURL(''));
 (async()=>{if(!m||typeof m.type!=='string')throw Error('Invalid message');
 switch(m.type){
 case'CONNECT':if(!web&&!internal&&!sb)throw Error('Unauthorized sender');await connect(true,typeof m.payload?.program==='string'?String(m.payload.program).slice(0,240):undefined);return{ok:true};
 case'GET_SYNC':if(!apas)throw Error('Unauthorized sender');{const s=await chrome.storage.local.get(['syncTab','syncStarted','profile','requestedProgram']);return{preferredProgram:typeof s.requestedProgram==='string'?s.requestedProgram:(s.profile as StudentAcademicProfile|undefined)?.program.name,active:s.syncTab===sender.tab?.id&&Date.now()-Number(s.syncStarted)<180000};}
 case'APAS_CHOICES':if(!apas)throw Error('Unauthorized sender');{const s=await chrome.storage.local.get('syncTab');if(s.syncTab!==sender.tab?.id)throw Error('Unowned sync tab');const programs=Array.isArray(m.programs)?[...new Set(m.programs.filter((x:unknown)=>typeof x==='string').map((x:string)=>x.slice(0,240)))].slice(0,20):[];await chrome.storage.local.set({availablePrograms:programs});return{ok:true};}
 case'APAS_RESULT':if(!apas)throw Error('Unauthorized sender');{const s=await chrome.storage.local.get(['syncTab','profile']);if(s.syncTab!==sender.tab?.id)throw Error('Unowned sync tab');const p=academicProfile(m.profile);if(!p||!p.requirements.length)throw Error('Invalid normalized audit');const current=academicProfile(s.profile),next=mergeProgramAudit(current,p),count=1+(next.additionalPrograms?.length||0);await chrome.storage.local.set({profile:next,status:`UMN Connected · ${count} APAS program${count===1?'':'s'} imported`});await chrome.storage.local.remove(['syncTab','requestedProgram']);if(sender.tab?.id)await chrome.tabs.remove(sender.tab.id);return{ok:true};}
 case'APAS_ERROR':if(!apas)throw Error('Unauthorized sender');await chrome.storage.local.set({status:String(m.message).slice(0,250)});return{ok:true};
 case'GET_STATE':if(!web&&!internal)throw Error('Unauthorized sender');{const state=await chrome.storage.local.get(['profile','plans','status','availablePrograms','storageVersion']);return{...state,profile:state.storageVersion===undefined||state.storageVersion===0||state.storageVersion===STORAGE_VERSION?academicProfile(state.profile):undefined,plans:state.storageVersion===undefined||state.storageVersion===0||state.storageVersion===STORAGE_VERSION?savedPlans(state.plans):[]};}
 case'FORGET':if(!web&&!internal)throw Error('Unauthorized sender');await chrome.storage.local.remove(['profile','plans','status','availablePrograms','requestedProgram']);return{ok:true};
 case'SAVE_PROFILE':if(!web&&!internal)throw Error('Unauthorized sender');{const p=academicProfile(m.payload);if(!p||!p.requirements.length)throw Error('Invalid normalized audit');await chrome.storage.local.set({profile:p,status:'UMN Connected · local recovery import'});return{ok:true};}
 case'SAVE_PLANS':if(!web&&!internal)throw Error('Unauthorized sender');if(!Array.isArray(m.payload)||JSON.stringify(m.payload).length>1_000_000)throw Error('Invalid plans');await chrome.storage.local.set({plans:savedPlans(m.payload)});return{ok:true};
 case'CONTEXT_BATCH':if(!sb&&!internal)throw Error('Unauthorized sender');return batch(m.codes,m.term,m.campus);
 case'GET_FIT':if(!sb)throw Error('Unauthorized sender');{
  if(!Array.isArray(m.courses)||m.courses.length>12)throw Error('Invalid course fit batch');
  const courses=(m.courses as unknown[]).map(value=>{if(!value||typeof value!=='object')throw Error('Invalid course');const c=value as Course;courseCode(c.code);if(c.campus!=='UMNTC')throw Error('Smart UMN currently supports Twin Cities courses only');return c;});
  const state=await chrome.storage.local.get(['profile','status','storageVersion']);const profile=state.storageVersion===undefined||state.storageVersion===0||state.storageVersion===STORAGE_VERSION?academicProfile(state.profile):undefined;
  if(!profile)return{connected:false,status:String(state.status||''),items:courses.map(c=>({code:c.code,eligibility:{result:'unknown',reason:'Connect UMN to check prerequisites'},matches:[]}))};
  const{degreeFit,degreeCandidateFit,eligibility}=await import('../../packages/core/rules.ts');const enriched=new Map<string,StudentAcademicProfile>();for(const c of courses){const cp=campusCode(c.campus||'UMNTC'),t=termCode(c.term),key=cp+':'+t;if(enriched.has(key))continue;let effective=profile;try{const response=await fetch(WEB+'/api/general-education?campus='+encodeURIComponent(cp)+'&term='+encodeURIComponent(t),{signal:AbortSignal.timeout(12000)});if(response.ok){const evidence=await response.json();if(evidence.data&&!evidence.stale)effective=enrichGeneralEducation(profile,evidence.data);}}catch{}enriched.set(key,effective);}return{connected:true,status:String(state.status||'UMN Connected'),items:courses.map(c=>{const p=enriched.get(campusCode(c.campus||'UMNTC')+':'+termCode(c.term))||profile;return{code:c.code,eligibility:eligibility(c,p),matches:degreeFit(c,p),routes:degreeCandidateFit(c,p)};})};
 }
 default:throw Error('Unknown message');}
 })().then(respond).catch(err=>respond({error:err instanceof Error?err.message:'Extension error'}));return true;
});

chrome.storage.onChanged.addListener((changes,area)=>{
 if(area!=='local')return;
 void chrome.tabs.query({url:WEB+'/*'}).then(tabs=>Promise.allSettled(tabs.filter(t=>t.id!==undefined).map(t=>chrome.tabs.sendMessage(t.id!,{type:'STATE_CHANGED'}))));
 if(changes.profile||changes.status)void chrome.tabs.query({url:'https://schedulebuilder.umn.edu/*'}).then(tabs=>Promise.allSettled(tabs.filter(t=>t.id!==undefined).map(t=>chrome.tabs.sendMessage(t.id!,{type:'PERSONALIZATION_CHANGED'}))));
});
