import {courseCode,unknownRule,subjectCode} from '../schemas/index.ts';
import type {RequirementRule,Truth,StudentCourse,Course,DegreeRequirement,StudentAcademicProfile,UMNCampus} from '../schemas/index.ts';
export const and=(v:Truth[]):Truth=>v.includes('no')?'no':v.includes('unknown')?'unknown':'yes';
export const or=(v:Truth[]):Truth=>v.includes('yes')?'yes':v.includes('unknown')?'unknown':'no';
const grades:Record<string,number>={'A+':4,A:4,'A-':3.67,'B+':3.33,B:3,'B-':2.67,'C+':2.33,C:2,'C-':1.67,'D+':1.33,D:1,F:0};
export function passed(c:StudentCourse):boolean{
 if(!['completed','transfer'].includes(c.status))return false;
 const grade=(c.grade||'').trim().toUpperCase();
 if(grade)return grade in grades?grades[grade]>0:/^(S|P|T[0-9A-Z+-]*)$/.test(grade);
 // AP/IB/test or other transfer credit already articulated by APAS may not carry
 // a letter/transfer grade. A positive-credit mapped transfer row is still
 // authoritative evidence that UMN awarded the equivalent course credit.
 return c.status==='transfer'&&!!c.transferSource&&typeof c.credits==='number'&&c.credits>0;
}
type MatchCourse=Pick<Course,'code'|'subject'|'catalogNumber'> & Partial<Pick<Course,'campus'|'attributes'>>;
function campusMatch(ruleCampus:UMNCampus|undefined,campus:UMNCampus|undefined):Truth{return!ruleCampus?'yes':!campus?'unknown':ruleCampus===campus?'yes':'no';}
export function courseAttributePairs(attributes:string[]|undefined):{attribute:string;value:string;name?:string}[]{const out:{attribute:string;value:string;name?:string}[]=[];for(const raw of attributes||[]){try{const a=JSON.parse(raw);if(a&&typeof a==='object'&&typeof a.attribute==='string'&&typeof a.attribute_value==='string')out.push({attribute:a.attribute,value:a.attribute_value,name:typeof a.name==='string'?a.name:undefined});}catch{}}return out;}
export function matches(rule:RequirementRule,c:MatchCourse):Truth {
 switch(rule.type){case'unknown':case'policy':return'unknown';case'course':{const cm=campusMatch(rule.campus,c.campus);return cm==='no'?'no':rule.code!==c.code?'no':cm;}case'range':{const cm=campusMatch(rule.campus,c.campus);if(cm==='no')return'no';const n=parseInt(c.catalogNumber);const hit=c.subject===rule.subject&&n>=rule.min&&n<=rule.max&&(!rule.suffix||c.catalogNumber.endsWith(rule.suffix));return hit?cm:'no';}case'attribute':{const cm=campusMatch(rule.campus,c.campus);if(cm==='no')return'no';if(!c.attributes)return'unknown';const hit=courseAttributePairs(c.attributes).some(a=>a.attribute===rule.attribute&&a.value===rule.value);return hit?cm:'no';}case'anyOf':return or(rule.rules.map(r=>matches(r,c)));case'allOf':return and(rule.rules.map(r=>matches(r,c)));case'exclude':{const e=or(rule.excluded.map(r=>matches(r,c)));return e==='yes'?'no':e==='unknown'?'unknown':matches(rule.rule,c);}case'credits':case'count':case'gpa':return matches(rule.rule,c);}
}
export function evaluate(rule:RequirementRule,courses:StudentCourse[]):Truth {
 const done=courses.filter(passed);
 switch(rule.type){case'unknown':case'policy':return'unknown';case'course':{const sameCode=done.filter(c=>c.courseCode===rule.code);if(!sameCode.length)return'no';const found=rule.campus?sameCode.filter(c=>c.campus===rule.campus):sameCode;if(rule.campus&&!found.length)return sameCode.some(c=>!c.campus)?'unknown':'no';if(!rule.minimumGrade)return'yes';return or(found.map(c=>c.grade! in grades ? (grades[c.grade!]>=grades[rule.minimumGrade!]?'yes':'no'):'unknown'));}
 case'anyOf':return or(rule.rules.map(r=>evaluate(r,done)));case'allOf':return and(rule.rules.map(r=>evaluate(r,done)));
 case'credits':case'count':case'gpa':{const selected=done.filter(c=>c.courseCode&&matches(rule.rule,{code:c.courseCode,campus:c.campus,subject:c.subject||c.courseCode.split(' ')[0],catalogNumber:c.number||c.courseCode.split(' ')[1]})==='yes');const unique=[...new Map(selected.map(c=>[c.courseCode,c])).values()];if(rule.type==='count')return unique.length>=rule.minimum&&(rule.maximum===undefined||unique.length<=rule.maximum)?'yes':'no';if(unique.some(c=>c.credits===undefined))return'unknown';let credits=unique.reduce((s,c)=>s+c.credits!,0);if(rule.type==='credits')return credits>=rule.minimum&&(rule.maximum===undefined||credits<=rule.maximum)?'yes':'no';if(!credits||unique.some(c=>!(c.grade! in grades)))return'unknown';return unique.reduce((s,c)=>s+c.credits!*grades[c.grade!],0)/credits>=rule.minimum?'yes':'no';}
 default:return done.some(c=>c.courseCode&&matches(rule,{code:c.courseCode,campus:c.campus,subject:c.subject!,catalogNumber:c.number!})==='yes')?'yes':'no';
 }
}
// Recursive descent preserves AND/OR precedence and parentheses. Unrecognized atoms
// remain unknown, so an independently satisfied OR branch can still be proved.
export function parsePrerequisites(source:string,campus?:UMNCampus):RequirementRule {
 if(!source.trim())return unknownRule(source,'No prerequisite information supplied');
 let text=source.replace(/^.*?prereq\s*:\s*/i,'').replace(/^Update:\s*/i,'').replace(/[\[\{]/g,'(').replace(/[\]\}]/g,')').replace(/,\s*(or|and)\b/gi,' $1 ').trim();
 if(/^(none|no prerequisites)[.]?$/i.test(text))return{type:'allOf',rules:[]};
 const tokens=text.split(/(\(|\)|\band\b|\bor\b|&)/i).map(s=>s.trim()).filter(Boolean);let i=0;
 function atom():RequirementRule {const t=tokens[i++];if(t==='('){const r=disjunction();if(tokens[i++]!==')')throw Error();return r;}if(!t||t===')')throw Error();try{return{type:'course',code:courseCode(t),...(campus?{campus}:{})}}catch{return unknownRule(t,'Standing, consent, grade or other condition requires review');}}
 function conjunction():RequirementRule {const rs=[atom()];while(/^(and|&)$/i.test(tokens[i]||'')){i++;rs.push(atom());}return rs.length===1?rs[0]:{type:'allOf',rules:rs};}
 function disjunction():RequirementRule {const rs=[conjunction()];while(/^or$/i.test(tokens[i]||'')){i++;rs.push(conjunction());}return rs.length===1?rs[0]:{type:'anyOf',rules:rs};}
 try{const r=disjunction();return i===tokens.length?r:unknownRule(source);}catch{return unknownRule(source);}
}
export function flattenRequirements(rs:DegreeRequirement[]):DegreeRequirement[]{return rs.flatMap(r=>[r,...flattenRequirements(r.children)]);}
export function profileRequirementRoots(profile?:StudentAcademicProfile):DegreeRequirement[]{return profile?[...profile.requirements,...(profile.additionalPrograms||[]).flatMap(p=>p.requirements)]:[];}
export type RequirementCoverageBucket='exactCourse'|'subjectRange'|'officialAttribute'|'credits'|'count'|'gpa'|'exclusions'|'nested'|'candidateOnly'|'unknown';
export type RequirementCoverageSummary={totalActiveRemainingRequirements:number;strictSupportedRequirements:number;candidateRouteSupportedRequirements:number;aggregateContainers:number;unknownUnroutedRequirements:number;policyConstraints:number;recognizedPolicyRules:number;unclassifiedPolicyConstraints:number;strictCoveragePercent:number;usefulRouteCoveragePercent:number;breakdown:Record<RequirementCoverageBucket,number>;unsupportedReasonHistogram:Record<string,number>};
export type ProgramRequirementCoverage={programName:string;programKind?:StudentAcademicProfile['program']['kind'];summary:RequirementCoverageSummary};
export type RequirementCoverageAnalysis={overall:RequirementCoverageSummary;programs:ProgramRequirementCoverage[]};
function ruleCanAuthorize(rule:RequirementRule):boolean{switch(rule.type){case'unknown':case'policy':return false;case'course':case'range':case'attribute':return true;case'anyOf':return rule.rules.some(ruleCanAuthorize);case'allOf':return rule.rules.every(ruleCanAuthorize);case'exclude':return ruleCanAuthorize(rule.rule)&&rule.excluded.every(r=>r.type!=='unknown'&&ruleCanAuthorize(r));case'credits':case'count':case'gpa':return ruleCanAuthorize(rule.rule);}}
function unknownReasons(rule:RequirementRule):string[]{switch(rule.type){case'unknown':return[rule.reason||'Unsupported or incomplete rule'];case'policy':return[rule.reason||`Recognized ${rule.family} policy is non-authorizing`];case'anyOf':case'allOf':return rule.rules.flatMap(unknownReasons);case'exclude':return[...unknownReasons(rule.rule),...rule.excluded.flatMap(unknownReasons)];case'credits':case'count':case'gpa':return unknownReasons(rule.rule);default:return[];}}
function coverageBucket(r:DegreeRequirement,strict:boolean,candidate:boolean):RequirementCoverageBucket{if(!strict&&candidate)return'candidateOnly';switch(r.rule.type){case'course':return'exactCourse';case'range':return'subjectRange';case'attribute':return'officialAttribute';case'credits':return'credits';case'count':return'count';case'gpa':return'gpa';case'exclude':return'exclusions';case'anyOf':case'allOf':return'nested';case'policy':return r.rule.family==='institutional-gpa'?'gpa':'credits';case'unknown':if(r.requiredGpa!==undefined)return'gpa';if(r.requiredCount!==undefined)return'count';if(r.requiredCredits!==undefined)return'credits';return'unknown';}}
function summarizeCoverage(requirements:DegreeRequirement[]):RequirementCoverageSummary{const open=flattenRequirements(requirements).filter(r=>r.status==='incomplete'||r.status==='in_progress');const breakdown:Record<RequirementCoverageBucket,number>={exactCourse:0,subjectRange:0,officialAttribute:0,credits:0,count:0,gpa:0,exclusions:0,nested:0,candidateOnly:0,unknown:0};const unsupportedReasonHistogram:Record<string,number>={};let strict=0,candidate=0,aggregate=0,unknown=0,policy=0,recognizedPolicy=0,unclassifiedPolicy=0;for(const r of open){const strictSupported=ruleCanAuthorize(r.rule),candidateSupported=!strictSupported&&!!r.candidateRule&&ruleCanAuthorize(r.candidateRule);if(strictSupported)strict++;else if(candidateSupported)candidate++;else if(r.children.length){aggregate++;}else{const policyConstraint=r.rule.type==='policy'||r.requiredCredits!==undefined||r.requiredCount!==undefined||r.requiredGpa!==undefined;if(policyConstraint){policy++;if(r.rule.type==='policy')recognizedPolicy++;else unclassifiedPolicy++;}else unknown++;const reasons=unknownReasons(r.rule);for(const reason of reasons.length?reasons:['Unsupported or incomplete rule'])unsupportedReasonHistogram[reason]=(unsupportedReasonHistogram[reason]||0)+1;}breakdown[coverageBucket(r,strictSupported,candidateSupported)]++;}const total=open.length,pct=(n:number)=>total?Number((n*100/total).toFixed(1)):100;return{totalActiveRemainingRequirements:total,strictSupportedRequirements:strict,candidateRouteSupportedRequirements:candidate,aggregateContainers:aggregate,unknownUnroutedRequirements:unknown,policyConstraints:policy,recognizedPolicyRules:recognizedPolicy,unclassifiedPolicyConstraints:unclassifiedPolicy,strictCoveragePercent:pct(strict),usefulRouteCoveragePercent:pct(strict+candidate),breakdown,unsupportedReasonHistogram:Object.fromEntries(Object.entries(unsupportedReasonHistogram).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])))};}
export function analyzeRequirementRouteCoverage(profile?:StudentAcademicProfile):RequirementCoverageAnalysis{if(!profile)return{overall:summarizeCoverage([]),programs:[]};const programs=[{program:profile.program,requirements:profile.requirements},...(profile.additionalPrograms||[]).map(p=>({program:p.program,requirements:p.requirements}))];return{overall:summarizeCoverage(programs.flatMap(p=>p.requirements)),programs:programs.map(p=>({programName:p.program.name,programKind:p.program.kind,summary:summarizeCoverage(p.requirements)}))};}
export function requirementRouteCoverage(profile?:StudentAcademicProfile){const summary=analyzeRequirementRouteCoverage(profile).overall;return{openRequirements:summary.totalActiveRemainingRequirements,strictRoutes:summary.strictSupportedRequirements,candidateRoutes:summary.candidateRouteSupportedRequirements,policyConstraints:summary.policyConstraints,unresolved:summary.unknownUnroutedRequirements};}
export function degreeFit(course:Course,profile?:StudentAcademicProfile):{requirementId:string;label:string;result:Truth}[]{if(!profile)return[];return flattenRequirements(profileRequirementRoots(profile)).filter(r=>r.status==='incomplete'||r.status==='in_progress').map(r=>({requirementId:r.id,label:r.label,result:matches(r.rule,course)})).filter(r=>r.result!=='no');}
export function degreeCandidateFit(course:Course,profile?:StudentAcademicProfile):{requirementId:string;label:string;result:Truth;strict:boolean}[]{if(!profile)return[];return flattenRequirements(profileRequirementRoots(profile)).filter(r=>r.status==='incomplete'||r.status==='in_progress').map(r=>{const strict=matches(r.rule,course);const candidate=r.candidateRule?matches(r.candidateRule,course):strict;return{requirementId:r.id,label:r.label,result:strict==='yes'?'yes':candidate,strict:strict==='yes'};}).filter(r=>r.result!=='no');}
export type DegreeDiscoveryPlan={explicitCodes:string[];subjects:string[];attributes:{attribute:string;value:string;name?:string}[]};
export function degreeDiscoveryPlan(profile?:StudentAcademicProfile,campus?:UMNCampus):DegreeDiscoveryPlan{
 const codes=new Set<string>(),subjects=new Set<string>(),attrs=new Map<string,{attribute:string;value:string;name?:string}>();if(!profile)return{explicitCodes:[],subjects:[],attributes:[]};
 const allowed=(ruleCampus?:UMNCampus)=>!campus||!ruleCampus||ruleCampus===campus;
 const visit=(rule:RequirementRule)=>{switch(rule.type){case'course':if(allowed(rule.campus))codes.add(courseCode(rule.code));break;case'range':if(allowed(rule.campus))subjects.add(subjectCode(rule.subject));break;case'attribute':if(allowed(rule.campus))attrs.set(`${rule.attribute}|${rule.value}`,{attribute:rule.attribute,value:rule.value,name:rule.name});break;case'anyOf':case'allOf':rule.rules.forEach(visit);break;case'exclude':visit(rule.rule);break;case'credits':case'count':case'gpa':visit(rule.rule);break;case'unknown':case'policy':break;}};
 for(const r of flattenRequirements(profileRequirementRoots(profile)))if(r.status==='incomplete'||r.status==='in_progress'){visit(r.rule);if(r.candidateRule)visit(r.candidateRule);}
 return{explicitCodes:[...codes].sort(),subjects:[...subjects].sort(),attributes:[...attrs.values()].sort((a,b)=>(a.name||a.value).localeCompare(b.name||b.value))};
}
// Catalog discovery is bounded before any grade/section context is fetched.
// Range subjects come first, followed by subjects with the most explicit routes.
export function degreeDiscoverySubjects(plan:DegreeDiscoveryPlan,limit=12):{subjects:string[];omitted:number}{
 if(!Number.isInteger(limit)||limit<1||limit>64)throw Error('Subject limit must be between 1 and 64');
 const counts=new Map<string,number>();
 for(const code of plan.explicitCodes){const subject=code.split(' ')[0];counts.set(subject,(counts.get(subject)||0)+1);}
 const all=[...new Set([...plan.subjects,...[...counts.keys()].sort((a,b)=>counts.get(b)!-counts.get(a)!||a.localeCompare(b))])];
 return{subjects:all.slice(0,limit),omitted:Math.max(0,all.length-limit)};
}
function sameStudentCourse(c:StudentCourse,course:Course){return c.courseCode===course.code&&(!c.campus||c.campus===course.campus);}
function sameStudentCode(c:StudentCourse,code:string,campus:UMNCampus){return c.courseCode===code&&(!c.campus||c.campus===campus);}
export function sortCoursesForProfile(courses:Course[],profile?:StudentAcademicProfile):Course[]{const rank=(c:Course)=>!profile?2:degreeFit(c,profile).some(f=>f.result==='yes')?0:degreeCandidateFit(c,profile).some(f=>f.result==='yes'&&!f.strict)?1:2;return[...courses].sort((a,b)=>rank(a)-rank(b)||a.code.localeCompare(b.code));}
export function discoverDegreeCandidates(courses:Course[],profile?:StudentAcademicProfile):Course[]{if(!profile)return[];const campus=courses[0]?.campus,exact=new Set(degreeDiscoveryPlan(profile,campus).explicitCodes),known=[...profile.completedCourses,...profile.inProgressCourses,...profile.transferCourses];return[...new Map(courses.map(c=>[`${c.campus}:${c.code}`,c])).values()].filter(c=>!known.some(s=>sameStudentCourse(s,c))&&eligibility(c,profile).result!=='no'&&degreeCandidateFit(c,profile).some(f=>f.result==='yes')).sort((a,b)=>Number(exact.has(b.code))-Number(exact.has(a.code))||Number(eligibility(b,profile).result==='yes')-Number(eligibility(a,profile).result==='yes')||Number(degreeFit(b,profile).some(f=>f.result==='yes'))-Number(degreeFit(a,profile).some(f=>f.result==='yes'))||a.code.localeCompare(b.code));}
export function eligibility(course:Course,profile?:StudentAcademicProfile):{result:Truth;reason:string}{if(!profile)return{result:'unknown',reason:'Connect UMN to check prerequisites'};const completed=[...profile.completedCourses,...profile.transferCourses];if(completed.some(c=>sameStudentCourse(c,course)&&passed(c)))return{result:'no',reason:'Already completed; duplicate credit excluded'};const completedEquivalent=completed.find(c=>passed(c)&&course.equivalents.some(code=>sameStudentCode(c,code,course.campus)));if(completedEquivalent)return{result:'no',reason:`Equivalent course ${completedEquivalent.courseCode} already completed; duplicate credit excluded`};if(profile.inProgressCourses.some(c=>sameStudentCourse(c,course)))return{result:'no',reason:'Already in progress'};const inProgressEquivalent=profile.inProgressCourses.find(c=>course.equivalents.some(code=>sameStudentCode(c,code,course.campus)));if(inProgressEquivalent)return{result:'no',reason:`Equivalent course ${inProgressEquivalent.courseCode} already in progress`};if(course.prerequisiteRule.type==='allOf'&&!course.prerequisiteRule.rules.length)return{result:'yes',reason:'No prerequisites'};const result=evaluate(course.prerequisiteRule,completed);return{result,reason:result==='yes'?'Prerequisites satisfied by completed courses':result==='no'?'Prerequisites not satisfied':'Prerequisite conditions need review'};}
