import fs from 'node:fs';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {chromium,type BrowserContext,type Page} from 'playwright-core';

const root=process.cwd(),base='http://127.0.0.1:4317/',runtime=path.join(root,'.runtime'),videoTmp=path.join(runtime,'demo-videos'),outDir=path.join(root,'docs/demos');
const executable=path.join(runtime,'playwright-browsers/chromium-1193/chrome-mac/Chromium.app/Contents/MacOS/Chromium');
if(!fs.existsSync(executable))throw new Error('Demo Chromium is missing. Install Playwright Chromium into .runtime/playwright-browsers first.');
fs.mkdirSync(videoTmp,{recursive:true});fs.mkdirSync(outDir,{recursive:true});

const now=new Date().toISOString();
const completed=(courseCode:string)=>{const[subject,number]=courseCode.split(' ');return{courseCode,campus:'UMNTC',subject,number,credits:4,grade:'A',status:'completed'};};
const req=(id:string,code:string,label:string)=>({id,label,status:'incomplete',requiredCount:1,remainingCount:1,coursesUsed:[],children:[],rule:{type:'count',minimum:1,rule:{type:'course',code,campus:'UMNTC'}},rawMetadata:{demo:true}});
const demoProfile={program:{name:'Smart UMN Demo B.S. (synthetic)',kind:'degree',campus:'UMNTC',catalogYear:'Fall 2026'},degreeCredits:{required:120,completed:102,remaining:18},completedCourses:[completed('CSCI 2021'),completed('CSCI 2033'),completed('MATH 1271')],inProgressCourses:[],transferCourses:[],requirements:[req('demo-5302','CSCI 5302','Numerical methods demo requirement'),req('demo-4203','CSCI 4203','Architecture demo requirement'),req('demo-4707','CSCI 4707','Computing elective demo requirement'),{id:'demo-policy',label:'Demo residency policy',status:'incomplete',requiredCredits:15,remainingCredits:15,coursesUsed:[],children:[],rule:{type:'unknown',sourceText:'Demo residency policy',reason:'Residency policy requires institutional review'},rawMetadata:{demo:true}}],syncedAt:now,parserVersion:'demo-0.7.0',warnings:['Synthetic demo profile — not a student audit'],provenance:{source:'synthetic-demo',retrievedAt:now,period:'Demo only'}};

let ownedServer:ReturnType<typeof spawn>|undefined;
async function ensureServer(){try{const r=await fetch(base+'api/health');if(r.ok)return;}catch{}ownedServer=spawn(process.execPath,['apps/api/server.ts'],{cwd:root,stdio:'ignore'});const deadline=Date.now()+15000;while(Date.now()<deadline){try{const r=await fetch(base+'api/health');if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('Smart UMN server did not start');}
function demoPrefs(){return{minCredits:3,maxCredits:6,fewestDays:true,noFriday:true,minimumTransitionMinutes:10};}
async function seed(page:Page){await page.goto(base);await page.evaluate(({profile,prefs})=>{localStorage.clear();localStorage.setItem('umn.profile',JSON.stringify(profile));localStorage.setItem('umn.term','1273');localStorage.setItem('umn.preferences',JSON.stringify(prefs));location.hash='Plan';},{profile:demoProfile,prefs:demoPrefs()});await page.reload();await page.waitForSelector('#autobuild');}
async function buildPlan(page:Page){await page.locator('#autobuild').click();await page.waitForSelector('.schedule',{timeout:90000});await page.waitForTimeout(1200);}
async function finalize(context:BrowserContext,page:Page,name:string){const video=page.video();await context.close();if(!video)throw new Error(`No video recorded for ${name}`);const raw=await video.path();const mp4=path.join(outDir,name+'.mp4');fs.rmSync(mp4,{force:true});const ff=spawnSync('ffmpeg',['-y','-loglevel','error','-i',raw,'-c:v','libx264','-preset','veryfast','-crf','25','-pix_fmt','yuv420p','-movflags','+faststart',mp4],{stdio:'inherit'});if(ff.status!==0)throw new Error(`ffmpeg conversion failed for ${name}`);fs.rmSync(raw,{force:true});const size=fs.statSync(mp4).size;if(size>20_000_000)throw new Error(`${name} demo is unexpectedly large: ${size}`);return{file:path.relative(root,mp4),bytes:size};}
async function newWebContext(){const browser=await chromium.launch({headless:true,executablePath:executable});const context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:videoTmp,size:{width:1280,height:720}}});return{browser,context,page:await context.newPage()};}

async function planDemo(){const{browser,context,page}=await newWebContext();await seed(page);await page.waitForTimeout(900);await buildPlan(page);await page.locator('.roadmap').scrollIntoViewIfNeeded();await page.waitForTimeout(2200);await page.locator('.schedule').scrollIntoViewIfNeeded();await page.waitForTimeout(1800);await page.locator('.why-plan').scrollIntoViewIfNeeded();await page.waitForTimeout(1400);await page.locator('.registration-handoff').scrollIntoViewIfNeeded();await page.waitForTimeout(2200);const result=await finalize(context,page,'01-plan-roadmap-registration');await browser.close();return result;}
async function whatIfDemo(){const{browser,context,page}=await newWebContext();await seed(page);await buildPlan(page);const prefs=page.locator('#preferences');await prefs.scrollIntoViewIfNeeded();await page.locator('#preferences > summary').click();await page.locator('.what-if > summary').click();await page.waitForTimeout(1000);await page.locator('#include-summer').check();await page.waitForTimeout(1400);await page.locator('#roadmap-credits').fill('3');await page.locator('#roadmap-credits').dispatchEvent('change');await page.waitForTimeout(1400);const drop=page.locator('#drop-course');if(await drop.count()){const values=await drop.locator('option').allTextContents();if(values.length>1)await drop.selectOption({index:1});}await page.waitForTimeout(1600);await page.locator('.roadmap').scrollIntoViewIfNeeded();await page.waitForTimeout(2600);const result=await finalize(context,page,'02-what-if-graduation');await browser.close();return result;}
async function extensionDemo(){const profileDir=path.join(runtime,'demo-extension-profile');fs.rmSync(profileDir,{recursive:true,force:true});const context=await chromium.launchPersistentContext(profileDir,{headless:true,executablePath:executable,viewport:{width:1280,height:720},recordVideo:{dir:videoTmp,size:{width:1280,height:720}},args:[`--disable-extensions-except=${path.join(root,'dist/extension')}`,`--load-extension=${path.join(root,'dist/extension')}`]});let worker=context.serviceWorkers()[0];if(!worker)worker=await context.waitForEvent('serviceworker',{timeout:15000});await worker.evaluate(async({profile})=>{await chrome.storage.local.set({profile,status:'UMN Connected · synthetic demo'});},{profile:demoProfile});const page=context.pages()[0]||await context.newPage();await page.goto('https://schedulebuilder.umn.edu/explore/2027Spring/CSCI/5302/');await page.waitForSelector('smart-umn-insight[data-course="CSCI 5302"]',{timeout:60000});const host=page.locator('smart-umn-insight[data-course="CSCI 5302"]');await host.scrollIntoViewIfNeeded();await page.waitForTimeout(2200);await host.evaluate((el:any)=>el.shadowRoot?.querySelector('[data-insight="degree"]')?.click());await page.waitForTimeout(1600);await host.evaluate((el:any)=>el.shadowRoot?.querySelector('[data-insight^="course-grades"]')?.click());await page.waitForTimeout(1600);await host.evaluate((el:any)=>el.shadowRoot?.querySelector('[data-insight="references"]')?.click());await page.waitForTimeout(2200);return await finalize(context,page,'03-schedulebuilder-extension');}

await ensureServer();
const results=[];try{results.push(await planDemo());results.push(await whatIfDemo());results.push(await extensionDemo());}finally{ownedServer?.kill('SIGTERM');}
const report={generatedAt:new Date().toISOString(),profile:'synthetic demo only',privacy:'No raw APAS HTML, student identity, credentials, cookies, Duo/SAML data, or personal course history is recorded.',videos:results};
fs.writeFileSync(path.join(outDir,'demo-manifest.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
