import fs from 'node:fs';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {chromium,type BrowserContext,type Page} from 'playwright-core';

const root=process.cwd(),base='http://127.0.0.1:4317/',runtime=path.join(root,'.runtime'),videoTmp=path.join(runtime,'demo-videos'),outDir=path.join(root,'docs/demos');
const executable=path.join(runtime,'playwright-browsers/chromium-1193/chrome-mac/Chromium.app/Contents/MacOS/Chromium');
if(!fs.existsSync(executable))throw new Error('Demo Chromium is missing. Install Playwright Chromium into .runtime/playwright-browsers first.');
fs.mkdirSync(videoTmp,{recursive:true});fs.mkdirSync(outDir,{recursive:true});

const now=new Date().toISOString();
const completed=(courseCode:string)=>{const[subject,number]=courseCode.split(' ');return{courseCode,campus:'UMNTC',subject,number,credits:4,grade:'A',status:'completed'};};
const req=(id:string,code:string,label:string)=>({id,label,status:'incomplete',requiredCount:1,remainingCount:1,coursesUsed:[],children:[],rule:{type:'count',minimum:1,rule:{type:'course',code,campus:'UMNTC'}},rawMetadata:{demo:true}});
const demoProfile={program:{name:'Smart UMN Demo B.S. (synthetic)',kind:'degree',campus:'UMNTC',catalogYear:'Fall 2026'},degreeCredits:{required:120,completed:102,remaining:18},completedCourses:[completed('CSCI 2021'),completed('CSCI 2033'),completed('MATH 1271')],inProgressCourses:[],transferCourses:[],requirements:[req('demo-5302','CSCI 5302','Numerical methods demo requirement'),req('demo-4203','CSCI 4203','Architecture demo requirement'),req('demo-4707','CSCI 4707','Computing elective demo requirement'),{id:'demo-policy',label:'Demo residency policy',status:'incomplete',requiredCredits:15,remainingCredits:15,coursesUsed:[],children:[],rule:{type:'unknown',sourceText:'Demo residency policy',reason:'Residency policy requires institutional review'},rawMetadata:{demo:true}}],syncedAt:now,parserVersion:'demo-0.9.7',warnings:['Synthetic demo profile — not a student audit'],provenance:{source:'synthetic-demo',retrievedAt:now,period:'Demo only'}};

let ownedServer:ReturnType<typeof spawn>|undefined;
async function ensureServer(){try{const r=await fetch(base+'api/health');if(r.ok)return;}catch{}ownedServer=spawn(process.execPath,['apps/api/server.ts'],{cwd:root,stdio:'ignore'});const deadline=Date.now()+15000;while(Date.now()<deadline){try{const r=await fetch(base+'api/health');if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('Smart UMN server did not start');}
function demoPrefs(){return{minCredits:3,maxCredits:6,fewestDays:true,noFriday:true,minimumTransitionMinutes:10};}
async function seed(page:Page){await page.goto(base);await page.evaluate(({profile,prefs})=>{localStorage.clear();localStorage.setItem('umn.profile',JSON.stringify(profile));localStorage.setItem('umn.term','1273');localStorage.setItem('umn.preferences',JSON.stringify(prefs));location.hash='Plan';},{profile:demoProfile,prefs:demoPrefs()});await page.reload();await page.waitForSelector('#autobuild');}
async function buildPlan(page:Page){await page.locator('#autobuild').click();await page.waitForSelector('.schedule',{timeout:90000});await page.waitForTimeout(1200);}
async function finalize(context:BrowserContext,page:Page,name:string){const video=page.video();await context.close();if(!video)throw new Error(`No video recorded for ${name}`);const raw=await video.path();const mp4=path.join(outDir,name+'.mp4');fs.rmSync(mp4,{force:true});const ff=spawnSync('ffmpeg',['-y','-loglevel','error','-i',raw,'-c:v','libx264','-preset','veryfast','-crf','25','-pix_fmt','yuv420p','-movflags','+faststart',mp4],{stdio:'inherit'});if(ff.status!==0)throw new Error(`ffmpeg conversion failed for ${name}`);fs.rmSync(raw,{force:true});const size=fs.statSync(mp4).size;if(size>20_000_000)throw new Error(`${name} demo is unexpectedly large: ${size}`);return{file:path.relative(root,mp4),bytes:size};}
async function newWebContext(){const browser=await chromium.launch({headless:true,executablePath:executable});const context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:videoTmp,size:{width:1280,height:720}}});return{browser,context,page:await context.newPage()};}

async function advisorDemo(){const{browser,context,page}=await newWebContext();await seed(page);await page.locator('.advisor-brief').scrollIntoViewIfNeeded();await page.waitForTimeout(2200);await buildPlan(page);await page.locator('.advisor-brief').scrollIntoViewIfNeeded();await page.waitForTimeout(2200);await page.locator('.schedule').scrollIntoViewIfNeeded();await page.waitForTimeout(1400);await page.locator('.registration-handoff').scrollIntoViewIfNeeded();await page.waitForTimeout(2200);const result=await finalize(context,page,'01-web-registration-advisor');await browser.close();return result;}
async function whatIfDemo(){const{browser,context,page}=await newWebContext();await seed(page);await buildPlan(page);const prefs=page.locator('#preferences');await prefs.scrollIntoViewIfNeeded();await page.locator('#preferences > summary').click();await page.locator('.what-if > summary').click();await page.waitForTimeout(1000);await page.locator('#include-summer').check();await page.waitForTimeout(1400);await page.locator('#roadmap-credits').fill('3');await page.locator('#roadmap-credits').dispatchEvent('change');await page.waitForTimeout(1400);const drop=page.locator('#drop-course');if(await drop.count()){const values=await drop.locator('option').allTextContents();if(values.length>1)await drop.selectOption({index:1});}await page.waitForTimeout(1600);await page.locator('.roadmap').scrollIntoViewIfNeeded();await page.waitForTimeout(2600);const result=await finalize(context,page,'02-web-what-if-advisor');await browser.close();return result;}
function ensureCommunityDemoData(){const commands=[['import-reviewed-link','CSCI 5302','https://www.reddit.com/r/uofmn/comments/kal74z/','CSCI 5302 with Daniel Boley?','his lectures were kinda dreary and went pretty high level but the tests and quizzes were wayyy easier than the homework.','2020-12-10'],['import-instructor-link','Daniel Boley','https://www.ratemyprofessors.com/professor/309254','Daniel Boley at University of Minnesota - Twin Cities']];for(const args of commands){const result=spawnSync(process.execPath,['apps/worker/cli.ts',...args],{cwd:root,stdio:'ignore'});if(result.status!==0)throw new Error(`Could not seed public reviewed demo reference: ${args[0]}`);}}
async function extensionDemo(){ensureCommunityDemoData();const profileDir=path.join(runtime,'demo-extension-profile');fs.rmSync(profileDir,{recursive:true,force:true});const context=await chromium.launchPersistentContext(profileDir,{headless:true,executablePath:executable,viewport:{width:1280,height:720},recordVideo:{dir:videoTmp,size:{width:1280,height:720}},args:[`--disable-extensions-except=${path.join(root,'dist/extension')}`,`--load-extension=${path.join(root,'dist/extension')}`]});let worker=context.serviceWorkers().find(w=>w.url().startsWith('chrome-extension://')&&w.url().endsWith('/background.js'));if(!worker)worker=await context.waitForEvent('serviceworker',{predicate:w=>w.url().startsWith('chrome-extension://')&&w.url().endsWith('/background.js'),timeout:15000});const page=context.pages()[0]||await context.newPage();await page.goto(base);await page.waitForSelector('#connection');await page.evaluate(profile=>window.postMessage({channel:'smart-umn-web',type:'SAVE_PROFILE',payload:profile},location.origin),demoProfile);await page.waitForFunction(()=>document.querySelector('#connection')?.textContent?.includes('APAS connected'),undefined,{timeout:15000});await page.goto('https://schedulebuilder.umn.edu/explore/2027Spring/CSCI/5302/');await page.waitForSelector('smart-umn-insight[data-course="CSCI 5302"]',{timeout:60000});const host=page.locator('smart-umn-insight[data-course="CSCI 5302"]');await host.scrollIntoViewIfNeeded();await page.waitForTimeout(2200);await host.evaluate((el:any)=>el.shadowRoot?.querySelector('[data-insight="course-grades"]')?.click());await page.waitForTimeout(2200);await host.evaluate((el:any)=>el.shadowRoot?.querySelector('[data-insight="offering-history"]')?.click());await page.waitForTimeout(1800);await host.evaluate((el:any)=>el.shadowRoot?.querySelector('[data-insight="instructor-intelligence"]')?.click());await page.waitForTimeout(3000);return await finalize(context,page,'03-extension-course-intelligence');}

await ensureServer();
function mediaDuration(file:string){const p=spawnSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',file],{encoding:'utf8'});if(p.status!==0)throw new Error(`ffprobe failed for ${file}`);return Number(p.stdout.trim());}
function makeShowcase(results:{file:string;bytes:number}[]){const thumbnails:string[]=[],previews:string[]=[];for(const[index,item]of results.entries()){const file=path.join(root,item.file),name=path.basename(file,'.mp4'),thumb=path.join(outDir,`${name}-thumb.png`),at=index===0?1.5:Math.max(.3,mediaDuration(file)/2);const shot=spawnSync('ffmpeg',['-y','-loglevel','error','-ss',String(at),'-i',file,'-frames:v','1',thumb],{stdio:'inherit'});if(shot.status!==0)throw new Error(`thumbnail failed for ${name}`);thumbnails.push(path.relative(root,thumb));const preview=path.join(outDir,`${name}-preview.gif`),start=index===1?'2':'0.6',filter='fps=10,scale=800:-2:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=144:stats_mode=diff[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle';const p=spawnSync('ffmpeg',['-y','-loglevel','error','-ss',start,'-t','5','-i',file,'-filter_complex',filter,preview],{stdio:'inherit'});if(p.status!==0)throw new Error(`preview GIF failed for ${name}`);if(fs.statSync(preview).size>4_500_000)throw new Error(`${name} preview GIF exceeds 4.5 MB budget`);previews.push(path.relative(root,preview));}const gif=path.join(outDir,'smart-umn-readme-demo.gif'),inputs=results.flatMap((item,i)=>['-ss',i===1?'2.5':'1','-t','4','-i',path.join(root,item.file)]),filter='[0:v]fps=12,scale=960:-2:flags=lanczos,setsar=1[v0];[1:v]fps=12,scale=960:-2:flags=lanczos,setsar=1[v1];[2:v]fps=12,scale=960:-2:flags=lanczos,setsar=1[v2];[v0][v1][v2]concat=n=3:v=1:a=0,split[s0][s1];[s0]palettegen=max_colors=192:stats_mode=diff[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle';const run=spawnSync('ffmpeg',['-y','-loglevel','error',...inputs,'-filter_complex',filter,gif],{stdio:'inherit'});if(run.status!==0)throw new Error('README GIF generation failed');if(fs.statSync(gif).size>8_000_000)throw new Error('README GIF exceeds 8 MB budget');return{gif:path.relative(root,gif),thumbnails,previews};}
const results=[];try{results.push(await advisorDemo());results.push(await whatIfDemo());results.push(await extensionDemo());}finally{ownedServer?.kill('SIGTERM');}
const showcase=makeShowcase(results);const report={generatedAt:new Date().toISOString(),profile:'synthetic academic profile only',publicEvidence:'Live public UMN/Schedule Builder/GopherGrades evidence plus manually reviewed original community links.',privacy:'No raw APAS HTML, student identity, credentials, cookies, Duo/SAML data, or personal course history is recorded.',videos:results,showcase};
fs.writeFileSync(path.join(outDir,'demo-manifest.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
