import fs from'node:fs';import path from'node:path';
import{publicCourseCoverageMarkdown,summarizePublicCourseCoverage}from'../packages/core/course-coverage.ts';
const jsonPath=path.resolve(process.argv[2]||'docs/evidence/course-intelligence-coverage.json'),mdPath=path.resolve(process.argv[3]||'docs/COURSE_INTELLIGENCE_COVERAGE.md');
if(!fs.existsSync(jsonPath))throw new Error('Course Intelligence coverage evidence missing: '+jsonPath);if(!fs.existsSync(mdPath))throw new Error('Course Intelligence coverage dashboard missing: '+mdPath);
const raw=JSON.parse(fs.readFileSync(jsonPath,'utf8'));if(raw?.scope!=='UMN Twin Cities'||typeof raw.checkedAt!=='string'||!Number.isFinite(Date.parse(raw.checkedAt))||typeof raw.term!=='string'||!/^1\d{2}[359]$/.test(raw.term)||!Array.isArray(raw.bySubject))throw new Error('Invalid course coverage snapshot header');
const subjects=new Set<string>();for(const row of raw.bySubject){if(!row||typeof row.subject!=='string'||!/^[A-Z]{2,8}$/.test(row.subject)||subjects.has(row.subject))throw new Error('Invalid or duplicate subject row');subjects.add(row.subject);for(const key of ['currentCourses','gradeCoveredCourses','descriptionCourses','creditsKnownCourses','sectionIndexedCourses','publishedPrerequisiteCourses','fullyDeterministicPrerequisiteCourses','partiallyStructuredPrerequisiteCourses','reviewOnlyPublishedPrerequisiteCourses','attributeTaggedCourses'])if(!Number.isInteger(row[key])||row[key]<0)throw new Error('Invalid '+key+' for '+row.subject);if(row.gradeCoveredCourses>row.currentCourses||row.descriptionCourses>row.currentCourses||row.creditsKnownCourses>row.currentCourses||row.sectionIndexedCourses>row.currentCourses||row.publishedPrerequisiteCourses>row.currentCourses||row.attributeTaggedCourses>row.currentCourses)throw new Error('Coverage count exceeds current course count for '+row.subject);if(row.fullyDeterministicPrerequisiteCourses+row.partiallyStructuredPrerequisiteCourses+row.reviewOnlyPublishedPrerequisiteCourses!==row.publishedPrerequisiteCourses)throw new Error('Prerequisite coverage buckets do not sum for '+row.subject);if(!['healthy','degraded','down'].includes(row.scheduleBuilderStatus)||!['available','missing','error'].includes(row.gopherGradesStatus))throw new Error('Invalid provider status for '+row.subject);}
if(!raw.community||raw.community.policy!=='curated-link-only'||!Number.isInteger(raw.community.courseReferences)||!Number.isInteger(raw.community.coursesWithReferences)||raw.community.courseReferences<0||raw.community.coursesWithReferences<0)throw new Error('Invalid community coverage summary');
const expected=summarizePublicCourseCoverage(raw.bySubject,raw.checkedAt,raw.term,{courseReferences:raw.community.courseReferences,coursesWithReferences:raw.community.coursesWithReferences});
if(JSON.stringify(expected)!==JSON.stringify(raw))throw new Error('Course Intelligence coverage aggregate drift; regenerate with npm run report:course-coverage');
const expectedMarkdown=publicCourseCoverageMarkdown(expected);if(fs.readFileSync(mdPath,'utf8')!==expectedMarkdown)throw new Error('Course Intelligence coverage dashboard is stale; regenerate from the evidence snapshot');
console.log(JSON.stringify({jsonPath,mdPath,checkedAt:raw.checkedAt,term:raw.term,subjects:raw.subjects,currentCourses:raw.currentCourses,official:raw.official,historical:raw.historical,community:raw.community},null,2));
