import{currentInstructorSignals,redditCourseSearch,safeCommunityLink}from'../community/signals.ts';
import type{CourseContext,StudentAcademicProfile,UMNCampus}from'../schemas/index.ts';import{instructorEntityKey}from'../schemas/index.ts';import{degreeCandidateFit,degreeFit,eligibility}from'../core/rules.ts';
export function escape(s:unknown):string{return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function date(s:string){return new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
export function termLabel(t:string){return`${{3:'Spring',5:'Summer',9:'Fall'}[Number(t.at(-1))]} ${2000+Number(t.slice(1,3))}`;}
export function sbLink(code:string,term:string,campus:UMNCampus='UMNTC'){const path=`explore/${termLabel(term).split(' ').reverse().join('')}/${encodeURIComponent(code.split(' ')[0])}/${encodeURIComponent(code.split(' ')[1])}/`;return campus==='UMNTC'?`https://schedulebuilder.umn.edu/${path}`:`https://schedulebuilder.umn.edu/redirect/${campus}/${path}`;}
const GPA_POINTS:Record<string,number>={'A+':4.333,A:4,'A-':3.667,'B+':3.333,B:3,'B-':2.667,'C+':2.333,C:2,'C-':1.667,'D+':1.333,D:1,'D-':0.667,F:0};
export type GradeDistributionSummary={students:number;gpa?:number;averageLetter?:string;mostCommon?:string;mostCommonPercent?:number};
export function gradeDistributionSummary(grades:Record<string,number>):GradeDistributionSummary{const entries=Object.entries(grades).filter(([,n])=>Number.isFinite(n)&&n>0),students=entries.reduce((s,[,n])=>s+n,0),impacting=entries.filter(([g])=>g in GPA_POINTS),impactingStudents=impacting.reduce((s,[,n])=>s+n,0),gpa=impactingStudents?impacting.reduce((s,[g,n])=>s+GPA_POINTS[g]*n,0)/impactingStudents:undefined,averageLetter=gpa===undefined?undefined:Object.entries(GPA_POINTS).reduce((best,[g,p])=>Math.abs(p-gpa)<Math.abs(GPA_POINTS[best]-gpa)?g:best,'A'),most=entries.sort((a,b)=>b[1]-a[1])[0];return{students,gpa:gpa===undefined?undefined:Number(gpa.toFixed(2)),averageLetter,mostCommon:most?.[0],mostCommonPercent:students&&most?Math.round(100*most[1]/students):undefined};}
export type InstructorGradeHistory={name:string;students:number;terms:string[];grades:Record<string,number>};
export function currentInstructorGradeHistory(c:CourseContext):InstructorGradeHistory[]{
 const current=[...new Map((c.sections.data||[]).flatMap(s=>s.instructors).map(i=>[i.id,i])).values()];const out:InstructorGradeHistory[]=[];
 for(const i of current){let key='';try{key=instructorEntityKey(i.name);}catch{continue;}const rows=c.grades.data?.distributions.filter(d=>d.instructorName&&instructorEntityKey(d.instructorName)===key)||[];if(!rows.length)continue;const grades:Record<string,number>={};for(const row of rows)for(const[g,n]of Object.entries(row.grades))grades[g]=(grades[g]||0)+n;out.push({name:i.name,students:rows.reduce((n,r)=>n+r.students,0),terms:[...new Set(rows.map(r=>r.term))].sort(),grades});}
 return out.sort((a,b)=>b.students-a.students);
}
export function referenceEntityLabel(c:CourseContext,entityType:string,entityId:string){if(entityType==='course')return'Course';const campus=c.course.data?.campus;for(const i of [...new Map((c.sections.data||[]).flatMap(s=>s.instructors).map(i=>[i.id,i])).values()]){try{if(instructorEntityKey(i.name,campus)===entityId||campus==='UMNTC'&&instructorEntityKey(i.name)===entityId)return i.name;}catch{}}return'Instructor';}
export function communityHTML(c:CourseContext){const code=c.course.data?.code||'',signals=currentInstructorSignals(c);return`<section class="community-evidence"><div class="community-heading"><div><small class="eyebrow">STUDENT PERSPECTIVES</small><h3>Beyond the grade.</h3></div><span class="evidence-label">Opinions, with context</span></div><p class="muted">Grades describe outcomes. Reviews describe experiences. Neither guarantees how a class will work for you.</p><div class="instructor-signals">${signals.map(s=>`<article class="instructor-signal"><div><h4>${escape(s.instructor.name)}</h4><small>Listed for ${termLabel(c.course.data!.term)} · Twin Cities</small></div><div class="rmp-metric">${s.rating?`<strong>${s.rating.quality.toFixed(1)}<small> / 5</small></strong><span>RMP overall quality</span>`:'<span class="muted">No matched rating available</span>'}</div>${s.rating?`<p class="metric-provenance">Via <a href="${escape(s.viaUrl)}" target="_blank" rel="noopener noreferrer">GopherGrades ↗</a> · ${c.grades.stale?'Cached copy · ':''}retrieved ${date(c.grades.provenance.retrievedAt)}<br>Rating count and rating update date not supplied. This is professor-wide, not a rating of this course.</p>`:''}<div class="community-links"><a href="${escape(s.originalUrl||s.searchUrl)}" target="_blank" rel="noopener noreferrer">${s.originalUrl?'Read RMP profile':'Find on RMP'} ↗</a><a href="${escape(s.redditUrl)}" target="_blank" rel="noopener noreferrer">Search professor discussions ↗</a></div></article>`).join('')||'<p class="muted">Current instructor is not available yet. No professor rating has been guessed.</p>'}</div><div class="discussion-heading"><h4>What students discuss</h4><a href="${escape(redditCourseSearch(code))}" target="_blank" rel="noopener noreferrer">Search r/uofmn for ${escape(code)} ↗</a></div><p class="muted">Look for workload, teaching style and assessments. Search links are discovery tools, not collected reviews.</p>${c.community.filter(r=>r.source!=='ratemyprofessor'&&safeCommunityLink(r.url)).map(r=>`<article class="reference"><small>${escape(referenceEntityLabel(c,r.entityType,r.entityId))} · ${escape(r.source)} · ${escape(r.publishedAt?.slice(0,10)||'Publication date unknown')}${r.publishedAt&&Date.now()-Date.parse(r.publishedAt)>730*86400000?' · Older than 2 years':''}</small><h4><a class="reference-title" href="${escape(safeCommunityLink(r.url))}" target="_blank" rel="noopener noreferrer">${escape(r.title)} ↗</a></h4>${r.excerpt?`<p>${escape(r.excerpt)}</p>`:'<p class="muted">Original link only; review text has not been collected.</p>'}<div class="topic-tags">${r.topics.map(t=>`<span>${escape(t)}</span>`).join('')}</div><small>${r.provenance.source.includes('reviewed-summary')?'Reviewed summary · ':''}Added ${date(r.discoveredAt)} · Individual experiences, not a representative survey</small></article>`).join('')||'<p class="muted">No collected Reddit discussion yet. Use the course or professor search above.</p>'}</section>`;}
function gradeBars(grades:Record<string,number>){const max=Math.max(...Object.values(grades),1);return`<div class="bars">${Object.entries(grades).map(([grade,count])=>`<div class="barrow"><span>${escape(grade)}</span><div><i style="width:${count/max*100}%"></i></div><span>${count.toLocaleString()}</span></div>`).join('')}</div>`;}
export function gradesHTML(c:CourseContext){const g=c.grades.data;if(!g)return'<p class="muted">Historical grades unavailable. Planning still works.</p>';const current=currentInstructorGradeHistory(c);return`${current.length?`<h3>Current instructor historical records</h3>${current.map(h=>`<section class="instructor-history"><strong>${escape(h.name)}</strong><p class="muted">${h.students.toLocaleString()} historical students · terms ${h.terms.map(escape).join(', ')}</p>${gradeBars(h.grades)}</section>`).join('')}`:''}<h3>Course-wide historical grades</h3><p>Based on ${g.totalStudents.toLocaleString()} historical students</p>${gradeBars(g.grades)}<p class="muted">GopherGrades · terms ${escape(c.grades.provenance.period)} · ${c.grades.stale?'Cached · ':''}updated ${date(c.grades.provenance.retrievedAt)}</p><p class="muted">Historical outcomes describe past cohorts; they do not predict your grade.</p>`;}
export function detailHTML(ctx:CourseContext,profile?:StudentAcademicProfile,tab='Overview') {const c=ctx.course.data;if(!c)return'<p>Course source unavailable. Please refresh later.</p>';const fits=degreeFit(c,profile).filter(f=>f.result==='yes'),routes=degreeCandidateFit(c,profile).filter(f=>f.result==='yes'&&!f.strict);const eligible=eligibility(c,profile);if(tab==='Grades')return gradesHTML(ctx);if(tab==='Community')return communityHTML(ctx);if(tab==='Degree')return`<h3>For your APAS plan</h3>${fits.length?fits.map(f=>`<p class="positive">✓ ${escape(f.label)}</p>`).join(''):routes.length?routes.map(f=>`<p class="warning">◇ ${escape(f.label)} · candidate route; APAS cap/policy still needs review</p>`).join(''):'<p class="muted">No proven course route to a remaining APAS requirement.</p>'}<p>${escape(eligible.reason)}</p><p class="muted">Major, minor, certificate, college and degree-wide policies can add caps or conditions. APAS remains the final authority.</p>`;
return`<p>${escape(c.description)}</p><div class="callout">${escape(eligible.reason)}${fits.length?'<br>✓ Matches an explicit remaining APAS course rule':''}</div><h3>Current sections</h3><p class="muted">${termLabel(c.term)} · Seats as of ${date(ctx.sections.provenance.retrievedAt)}${ctx.sections.stale?' · STALE — excluded from solver':''}</p>${(ctx.sections.data||[]).map(s=>`<article class="section"><div><strong>${escape(s.component)} ${escape(s.sectionNumber)}</strong><span class="pill ${s.open?'positive':''}">${s.open?'Open':'Closed'} · ${s.capacity!==undefined&&s.enrolled!==undefined?Math.max(0,s.capacity-s.enrolled):'?'} seats</span></div><p>${s.instructors.map(i=>escape(i.name)).join(', ')||'Instructor to be announced'} · ${escape(s.instructionMode)}</p><p>${s.meetings.map(m=>`${m.days.join('/')} ${m.startTime||'TBA'}–${m.endTime||'TBA'} · ${escape(m.location||'')}`).join('<br>')}</p>${s.restrictions.length?'<p class="warning">Registration restrictions need review</p>':''}${s.unresolvedLinks?'<p class="warning">Linked section rules need review</p>':''}</article>`).join('')||'<p>No sections available for this term.</p>'}<h3>Official UMN course feedback</h3><p class="muted">${escape(ctx.feedback.health.message)}</p><a href="${sbLink(c.code,c.term,c.campus)}" target="_blank" rel="noopener noreferrer">Open in Schedule Builder ↗</a>`;
}
