import{createHash}from'node:crypto';import type{CommunityReference,UMNCampus}from'../schemas/index.ts';import{courseCode,courseEntityKey,instructorEntityKey}from'../schemas/index.ts';
const topics=['workload','exam','homework','projects','attendance','lecture','grading','curve','organization','TA','textbook','online'];
export function neutralTopics(text:string){return topics.filter(t=>new RegExp(`\\b${t}\\b`,'i').test(text));}
export function canonicalURL(value:string){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error('Public HTTPS link required');if(!['www.reddit.com','reddit.com','www.ratemyprofessors.com'].includes(u.hostname))throw Error('Unsupported community host');u.hash='';u.search='';if(/reddit\.com$/.test(u.hostname)){u.hostname='www.reddit.com';const m=/^\/r\/([a-z0-9_]+)\/comments\/([a-z0-9]+)(?:\/[^/]+)?\/?$/i.exec(u.pathname);if(!m)throw Error('Expected an original Reddit discussion URL');u.pathname=`/r/${m[1]}/comments/${m[2]}/`;}return u.href;}
export function makeReference(entity:string,title:string,url:string,excerpt='',publishedAt?:string,method='manual-link',campus?:UMNCampus):CommunityReference{
 const code=courseCode(entity),entityId=courseEntityKey(code,campus);const canonical=canonicalURL(url);if(!canonical.includes('reddit.com'))throw Error('RateMyProfessors links must be attached to an instructor, not a course');if(!title.trim()||title.length>500)throw Error('Invalid title');const plain=title+' '+excerpt;const normalized=plain.toUpperCase().replace(/\s+/g,'');if(!normalized.includes(code.replace(' ','')))throw Error('Course association not supported by title/excerpt');
 const now=new Date().toISOString();const source=canonical.includes('reddit.com')?'reddit':'ratemyprofessor';return{id:createHash('sha256').update(canonical).digest('hex').slice(0,24),source,entityType:'course',entityId,title:title.trim(),url:canonical,excerpt:excerpt.trim().slice(0,280)||undefined,publishedAt,topics:neutralTopics(plain),sourceDocumentId:/\/comments\/([^/]+)/.exec(canonical)?.[1],discoveredAt:now,provenance:{source:`${source}:${method}`,url:canonical,retrievedAt:now,period:publishedAt||'Publication date not supplied'}};
}
export function makeInstructorReference(name:string,title:string,url:string,excerpt='',publishedAt?:string,method='manual-link',campus?:UMNCampus):CommunityReference{
 const entityId=instructorEntityKey(name,campus),canonical=canonicalURL(url);if(!title.trim()||title.length>500)throw Error('Invalid title');const plain=title+' '+excerpt;
 const evidence=plain.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');const wanted=name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
 if(!evidence.includes(wanted))throw Error('Instructor association not supported by title/excerpt');
 const source=canonical.includes('reddit.com')?'reddit':'ratemyprofessor';if(source==='ratemyprofessor'&&!/^\/professor\/\d+\/?$/i.test(new URL(canonical).pathname))throw Error('Expected an original RateMyProfessors professor URL');
 const now=new Date().toISOString();const sourceDocumentId=source==='ratemyprofessor'?/\/professor\/(\d+)/.exec(canonical)?.[1]:/\/comments\/([^/]+)/.exec(canonical)?.[1];return{id:createHash('sha256').update(canonical).digest('hex').slice(0,24),source,entityType:'instructor',entityId,title:title.trim(),url:canonical,excerpt:excerpt.trim().slice(0,280)||undefined,publishedAt,topics:neutralTopics(plain),sourceDocumentId,discoveredAt:now,provenance:{source:`${source}:${method}`,url:canonical,retrievedAt:now,period:publishedAt||'Publication date not supplied'}};
}
export function blockedPage(text:string){return /verify you are human|captcha|you.?ve been blocked|blocked by network security|access denied|log in to continue|sign in to continue/i.test(text);}
export function extractDiscussion(doc:Document,url:string,entity:string,campus?:UMNCampus):CommunityReference{const visible=doc.body?.textContent||'';if(blockedPage(visible))throw Error('Collection blocked; link-only fallback');const title=doc.querySelector('h1')?.textContent?.trim();if(!title)throw Error('Community extractor drift: missing title');const canonical=doc.querySelector<HTMLLinkElement>('link[rel=canonical]')?.href||url;if(new URL(canonical).hostname.replace('www.','')!==new URL(url).hostname.replace('www.',''))throw Error('Cross-site canonical rejected');const excerpt=doc.querySelector('[data-post-click-location="text-body"],.usertext-body,article p')?.textContent?.trim()||'';const publishedAt=doc.querySelector('time')?.getAttribute('datetime')||undefined;return makeReference(entity,title,canonical,excerpt,publishedAt,'rendered-dom',campus);}
