import{PARSER_VERSION}from'../../packages/apas-parser/index.ts';
import{readFileSync}from'node:fs';
import{serverConfig,requestAllowed,clientBudgetKey,RequestBudget,RequestError,readJSON}from'./security.ts';
import {createServer} from 'node:http';import{readFile}from'node:fs/promises';import{resolve,extname,sep}from'node:path';import{fileURLToPath}from'node:url';
import{Store}from'../../packages/providers/store.ts';import{ContextService}from'../../packages/providers/index.ts';import{campusCode,courseCode,subjectCode,termCode,record}from'../../packages/schemas/index.ts';import{createPolicyRetriever,policyDocumentsFromSnapshots}from'../../packages/retrieval/registry.ts';import{HybridPolicyRetriever,MiniLMEmbedder}from'../../packages/retrieval/policy.ts';
const ROOT=resolve(fileURLToPath(new URL('../..',import.meta.url)));const store=new Store(process.env.PLANNER_DB||resolve(ROOT,'var/planner.sqlite'));const context=new ContextService(store);const embeddingMode=process.env.SMART_UMN_EMBEDDINGS||'auto',policyEmbedder=embeddingMode==='off'?undefined:new MiniLMEmbedder(undefined,embeddingMode==='download'),policyClassifier=createPolicyRetriever([],policyEmbedder);let policySignature='',policyEvidence=new HybridPolicyRetriever([],policyEmbedder);function currentPolicyEvidence(){const snaps=store.policySnapshots(),sig=Math.floor(Date.now()/60000)+':'+snaps.map(s=>String(s.sourceHash||s.url||'')+':'+String(s.capturedAt||'')).sort().join('|');if(sig!==policySignature){policySignature=sig;policyEvidence=new HybridPolicyRetriever(policyDocumentsFromSnapshots(snaps),policyEmbedder);}return policyEvidence;}const config=serverConfig(),{port,origin}=config;const budget=new RequestBudget();let active=0;const metrics={requests:0,rejected:0,errors:0,latencyMs:0};
const version=JSON.parse(readFileSync(resolve(ROOT,'package.json'),'utf8')).version;
const mime:Record<string,string>={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.zip':'application/zip','.txt':'text/plain; charset=utf-8'};
export const server=createServer(async(req,res)=>{const started=Date.now();metrics.requests++;res.once('finish',()=>{metrics.latencyMs+=Date.now()-started;if(res.statusCode>=400)metrics.rejected++;});res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(config.production)res.setHeader('Strict-Transport-Security','max-age=31536000');res.setHeader('Cache-Control','no-store');
 const send=(status:number,data:unknown)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
 try{
 if(!requestAllowed(req,config))return send(403,{error:'Host or origin not allowed'});
 const from=req.headers.origin;
 if(from)res.setHeader('Access-Control-Allow-Origin',from);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');
 if(req.method==='OPTIONS'){res.writeHead(204);res.end();return;}
 if(!req.url?.startsWith('/')||req.url.startsWith('//')||req.url.length>4096)return send(400,{error:'Invalid request target'});
 const u=new URL(req.url,origin);
 if(u.pathname.startsWith('/api/')&&u.pathname!=='/api/health'){if(active>=32||!budget.take(clientBudgetKey(req,config))){res.setHeader('Retry-After','60');return send(429,{error:'Public evidence service busy; retry shortly'});}active++;res.once('close',()=>{active--;});}
 const term=()=>termCode(u.searchParams.get('term')||'1273'),campus=()=>{const c=campusCode(u.searchParams.get('campus')||'UMNTC');if(c!=='UMNTC')throw Error('Smart UMN currently supports Twin Cities Schedule Builder only');return c;};
 if(req.method==='GET'&&u.pathname==='/api/health')return send(200,{status:'running',version,parserVersion:PARSER_VERSION,localOnly:!config.production,providers:store.healthList(),metrics:{...metrics,active,providers:{scheduleBuilder:{...context.sb.stats},gopherGrades:{...context.gg.stats}}}});
 if(req.method==='GET'&&u.pathname==='/api/health/providers'){const providers=await Promise.all([context.sb.healthCheck(),context.gg.healthCheck()]);return send(200,{providers});}
 if(req.method==='GET'&&u.pathname==='/api/subjects')return send(200,await context.sb.fetchSubjects(campus()));
 const catalog=/^\/api\/catalog\/([^/]+)$/.exec(u.pathname);if(req.method==='GET'&&catalog){const subject=subjectCode(decodeURIComponent(catalog[1]));return send(200,await context.sb.fetchSubjectCourses(subject,term(),campus()));}
 const attribute=/^\/api\/attributes\/([^/]+)\/([^/]+)$/.exec(u.pathname);if(req.method==='GET'&&attribute){return send(200,await context.sb.fetchAttributeCourses(decodeURIComponent(attribute[1]),decodeURIComponent(attribute[2]),term(),campus()));}
 if(req.method==='GET'&&u.pathname==='/api/general-education')return send(200,await context.sb.fetchGeneralEducationCatalog(campus(),term()));
 if(req.method==='GET'&&u.pathname.startsWith('/api/courses/')){const bits=u.pathname.split('/');const code=courseCode(decodeURIComponent(bits[3]));const value=await context.get(code,term(),campus());return send(200,bits[4]==='sections'?value.sections:bits[4]==='context'?value:value.course);}
 if(req.method==='POST'){
 if(!['/api/course-context/batch','/api/policy/search'].includes(u.pathname))return send(404,{error:'Private academic data is not accepted by this API'});const input=record(await readJSON(req));
 if(u.pathname==='/api/course-context/batch'){if(Object.keys(input).some(k=>!['codes','term','campus'].includes(k))||!Array.isArray(input.codes)||(input.codes.length<1||input.codes.length>12)||input.codes.some((c:unknown)=>typeof c!=='string'))return send(400,{error:'Batch accepts 1–12 public course codes, campus and term only'});const t=termCode(String(input.term)),c=campusCode(String(input.campus||'UMNTC'));if(c!=='UMNTC')return send(400,{error:'Smart UMN currently supports Twin Cities Schedule Builder only'});const codes=[...new Set(input.codes.map((x:string)=>courseCode(x)))];return send(200,await Promise.all(codes.map(code=>context.get(code,t,c))));}
 if(u.pathname==='/api/policy/search'){if(Object.keys(input).some(k=>!['text','campus','college','program','catalogYear','limit'].includes(k)))return send(400,{error:'Policy search accepts only one rule text plus public program metadata'});if(typeof input.text!=='string'||!input.text.trim()||input.text.length>2000)return send(400,{error:'Policy search requires 1–2000 characters of rule text'});const c=campusCode(String(input.campus||'UMNTC'));if(c!=='UMNTC')return send(400,{error:'Policy retrieval currently supports Twin Cities only'});const clean=(v:unknown,max:number)=>typeof v==='string'?v.trim().slice(0,max)||undefined:undefined,limit=Math.max(1,Math.min(5,Number(input.limit)||3));const query={text:input.text.trim(),campus:c,college:clean(input.college,160),program:clean(input.program,240),catalogYear:clean(input.catalogYear,80),limit};const classification=await policyClassifier.search({...query,limit:1}),evidence=await currentPolicyEvidence().search({...query,limit});const semantic=[classification,evidence].some(x=>x.mode.endsWith('+minilm'));return send(200,{mode:semantic?'bounded-lexical+minilm':'bounded-lexical',classification:classification.matches[0]||null,evidence:evidence.matches,matches:[...(classification.matches[0]?[classification.matches[0]]:[]),...evidence.matches],queryFingerprint:classification.queryFingerprint,decisionAuthority:'none',note:'Semantic retrieval only. Classification and evidence do not authorize a course or satisfy a degree rule.'});}
 if(['/api/student/context','/api/student/plans','/api/recommendations','/api/schedules/generate'].includes(u.pathname))return send(409,{error:'Local-first mode: student context, plans and deterministic planning run in the browser. Private data is not accepted by this API.'});
 return send(404,{error:'Unknown endpoint'});
 }
 if(req.method!=='GET')return send(405,{error:'Method not allowed'});
 if(u.pathname.startsWith('/api/'))return send(404,{error:'Unknown endpoint'});
 const path=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname).slice(1);const target=resolve(ROOT,'dist/web',path);if(!target.startsWith(resolve(ROOT,'dist/web')+sep))return send(403,{error:'Invalid path'});
 res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
 const data=await readFile(target);res.writeHead(200,{'Content-Type':mime[extname(target)]||'application/octet-stream'});res.end(data);
 }catch(e){if((e as any)?.code==='ENOENT')return send(404,{error:'Not found'});metrics.errors++;send(e instanceof RequestError?e.status:400,{error:e instanceof RequestError?e.message:'Invalid request or unavailable evidence'});}
});
server.requestTimeout=15000;server.headersTimeout=10000;server.timeout=30000;server.maxHeadersCount=40;
server.listen(port,config.bind,()=>console.log(`Smart UMN Planner: ${origin}`));
for(const signal of ['SIGTERM','SIGINT'] as const)process.on(signal,()=>server.close(()=>{store.close();process.exit(0);}));
